# railway.toml
[build]
builder = "NIXPACKS"

[deploy]
# Define aqui o diretório onde estão main.py e requirements.txt
root = "backend"
# Comando para iniciar sua aplicação dentro de backend
start = "uvicorn main:app --host 0.0.0.0 --port 8000"
