[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  start = "python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"

[volumes]
  [[volumes.mounts]]
  source = "babix_volume"
  mountPath = "/mnt/data"
