[build]
  builder = "NIXPACKS"
  buildCommand = "pip install -r requirements.txt"

[deploy]
  start = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT}"

[variables]
  PYTHONUNBUFFERED = "1"
  PIP_DISABLE_PIP_VERSION_CHECK = "on"

[volumes]
  [[volumes.mounts]]
  source = "babix_volume"
  mountPath = "/mnt/data"
